In [1]:
import np as np
import pandas as pd
import scores as scores
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv ('../dataset.csv')
df['buggy'].value_counts()

0    7834
1      50
Name: buggy, dtype: int64

In [2]:
names_list = df['name'].tolist()
names_list

['src/java/org/apache/commons/compress/zip/ExtraFieldUtils.java',
 'src/java/org/apache/commons/compress/tar/TarBuffer.java',
 'src/java/org/apache/commons/compress/tar/TarEntry.java',
 'src/java/org/apache/commons/compress/zip/ZipLong.java',
 'src/java/org/apache/commons/compress/tar/TarOutputStream.java',
 'src/java/org/apache/commons/compress/zip/ZipShort.java',
 'src/java/org/apache/commons/compress/tar/TarInputStream.java',
 'src/java/org/apache/commons/compress/zip/UnixStat.java',
 'src/java/org/apache/commons/compress/zip/UnrecognizedExtraField.java',
 'src/java/org/apache/commons/compress/tar/TarUtils.java',
 'src/java/org/apache/commons/compress/zip/ZipEntry.java',
 'src/java/org/apache/commons/compress/zip/ZipOutputStream.java',
 'src/java/org/apache/commons/compress/zip/AsiExtraField.java',
 'src/java/org/apache/commons/compress/zip/ZipExtraField.java',
 'src/java/org/apache/commons/compress/tar/TarConstants.java',
 'src/java/org/apache/commons/compress/bzip2/CRC.java',
 'sr

In [3]:
df['class_commit_id'] = df['name'] + "_" + df['commit']

df.drop(df.columns[[0, 1]], axis=1, inplace=True)
df.drop_duplicates(inplace=True)

len(df)

7884

In [4]:
df['id'] = pd.Categorical(df['class_commit_id']).codes
df


number_of_authors      age  number_unique_changes  size  lines_added  \
0                     1        0                      1   250          249   
1                     1        0                      1   543          542   
2                     1        0                      1   734          733   
3                     1        0                      1   166          165   
4                     1        0                      1   470          469   
...                 ...      ...                    ...   ...          ...   
7879                  6   150165                     17   101            0   
7880                  2  2746021                      2    25            0   
7881                  8   150165                     19    96            0   
7882                  3  4525720                      3    28            0   
7883                 17    18938                    143  1485           19   

      lines_deleted  buggy                                    class_commit_id  \
0                 0      0  src/java/org/apache/commons/compress/zip/Extra...   
1                 0      0  src/java/org/apache/commons/compress/tar/TarBu...   
2                 0      0  src/java/org/apache/commons/compress/tar/TarEn...   
3                 0      0  src/java/org/apache/commons/compress/zip/ZipLo...   
4                 0      0  src/java/org/apache/commons/compress/tar/TarOu...   
...             ...    ...                                                ...   
7879              1      0  src/main/java/org/apache/commons/compress/arch...   
7880              1      0  src/main/java/org/apache/commons/compress/comp...   
7881              1      0  src/main/java/org/apache/commons/compress/util...   
7882              1      0  src/main/java/org/apache/commons/compress/arch...   
7883             14      0  src/main/java/org/apache/commons/compress/arch...   

        id  
0      263  
1      227  
2      237  
3      288  
4      248  
...    ...  
7879  2036  
7880  5232  
7881  7145  
7882  1550  
7883  3624  

[7884 rows x 9 columns]

In [5]:
df2 = df.drop(['class_commit_id'], axis=1)
df2

number_of_authors      age  number_unique_changes  size  lines_added  \
0                     1        0                      1   250          249   
1                     1        0                      1   543          542   
2                     1        0                      1   734          733   
3                     1        0                      1   166          165   
4                     1        0                      1   470          469   
...                 ...      ...                    ...   ...          ...   
7879                  6   150165                     17   101            0   
7880                  2  2746021                      2    25            0   
7881                  8   150165                     19    96            0   
7882                  3  4525720                      3    28            0   
7883                 17    18938                    143  1485           19   

      lines_deleted  buggy    id  
0                 0      0   263  
1                 0      0   227  
2                 0      0   237  
3                 0      0   288  
4                 0      0   248  
...             ...    ...   ...  
7879              1      0  2036  
7880              1      0  5232  
7881              1      0  7145  
7882              1      0  1550  
7883             14      0  3624  

[7884 rows x 8 columns]

In [6]:
X = df.iloc[:, 0:6]
y = df.iloc[:, 6:7]
y

buggy
0         0
1         0
2         0
3         0
4         0
...     ...
7879      0
7880      0
7881      0
7882      0
7883      0

[7884 rows x 1 columns]

In [7]:
X

number_of_authors      age  number_unique_changes  size  lines_added  \
0                     1        0                      1   250          249   
1                     1        0                      1   543          542   
2                     1        0                      1   734          733   
3                     1        0                      1   166          165   
4                     1        0                      1   470          469   
...                 ...      ...                    ...   ...          ...   
7879                  6   150165                     17   101            0   
7880                  2  2746021                      2    25            0   
7881                  8   150165                     19    96            0   
7882                  3  4525720                      3    28            0   
7883                 17    18938                    143  1485           19   

      lines_deleted  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
...             ...  
7879              1  
7880              1  
7881              1  
7882              1  
7883             14  

[7884 rows x 6 columns]

In [8]:
from joblib import dump, load
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


loaded_model = load('cv_results_NB.pkl')

import numpy as np

result_proba = loaded_model['estimator'][0].predict_proba(X.iloc[:1])
for i in range(1, len(loaded_model['estimator'])):
    result_proba = np.add(result_proba, loaded_model['estimator'][i].predict_proba(X))

result_proba = result_proba/10
print(np.array2string(result_proba, formatter={'float_kind':lambda x: "%.3f" % x}))

# y_pred = loaded_model.predict_proba(X)
# # print('Precision: %.3f' % precision_score(y, y_pred))
# # print('Recall: %.3f' % recall_score(y, y_pred))
# # print('F1: %.3f' % f1_score(y, y_pred))
# # print('Accuracy: %.3f' % accuracy_score(y, y_pred))

new_arr = np.delete(result_proba, 0, axis=1)


for i in range(len(new_arr)):
   new_arr[i] = int(100 * new_arr[i])


new_arr
arr_int = new_arr.astype(int)
arr_int

[[0.991 0.009]
 [0.998 0.002]
 [0.998 0.002]
 ...
 [0.612 0.388]
 [0.998 0.002]
 [0.998 0.002]]


array([[ 0],
       [ 0],
       [ 0],
       ...,
       [38],
       [ 0],
       [ 0]])

In [9]:
#for i in range(len(arr_int)):
#    arr_int[i] += 30

new_arr

array([[ 0.],
       [ 0.],
       [ 0.],
       ...,
       [38.],
       [ 0.],
       [ 0.]])

In [10]:


# Create a StringArray
string_array = np.array(names_list, dtype=str)

# Concatenate the two arrays horizontally
result = np.concatenate((string_array.reshape(-1,1), new_arr.reshape(-1,1)), axis=1)

# Remove quotation marks from strings
result[:, 0] = np.char.strip(result[:, 0], chars="'\"")

# Save result to file with .txt extension
np.savetxt('output.txt', result, delimiter=';', fmt='%s')

# Print the result
print(result)



[['src/java/org/apache/commons/compress/zip/ExtraFieldUtils.java' '0.0']
 ['src/java/org/apache/commons/compress/tar/TarBuffer.java' '0.0']
 ['src/java/org/apache/commons/compress/tar/TarEntry.java' '0.0']
 ...
 ['src/main/java/org/apache/commons/compress/utils/BoundedInputStream.java'
  '38.0']
 ['src/main/java/org/apache/commons/compress/archivers/sevenz/BindPair.java'
  '0.0']
 ['src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.java'
  '0.0']]


In [11]:
len(result)

7884

In [12]:
# dictionary to store unique classes and their probabilities
class_dict = {}

# iterate over original list
for item in result:
    class_name = item[0]
    prob = float(item[1])/100

    # check if class already exists in dictionary
    if class_name in class_dict:
        # calculate new probability using formula
        old_prob = class_dict[class_name]
        new_prob = 1 - (1 - old_prob) * (1 - prob)
        class_dict[class_name] = new_prob
    else:
        class_dict[class_name] = prob

# create new list with unique classes and their probabilities
new_list = [[class_name, str(60+ int(round(prob * 100, 1)))] for class_name, prob in class_dict.items()]

# print new list
for item in new_list:
    print(item)

len(new_list)

['src/java/org/apache/commons/compress/zip/ExtraFieldUtils.java', '99']
['src/java/org/apache/commons/compress/tar/TarBuffer.java', '125']
['src/java/org/apache/commons/compress/tar/TarEntry.java', '94']
['src/java/org/apache/commons/compress/zip/ZipLong.java', '104']
['src/java/org/apache/commons/compress/tar/TarOutputStream.java', '100']
['src/java/org/apache/commons/compress/zip/ZipShort.java', '105']
['src/java/org/apache/commons/compress/tar/TarInputStream.java', '126']
['src/java/org/apache/commons/compress/zip/UnixStat.java', '116']
['src/java/org/apache/commons/compress/zip/UnrecognizedExtraField.java', '99']
['src/java/org/apache/commons/compress/tar/TarUtils.java', '99']
['src/java/org/apache/commons/compress/zip/ZipEntry.java', '100']
['src/java/org/apache/commons/compress/zip/ZipOutputStream.java', '93']
['src/java/org/apache/commons/compress/zip/AsiExtraField.java', '100']
['src/java/org/apache/commons/compress/zip/ZipExtraField.java', '114']
['src/java/org/apache/commons/

681

In [13]:
# New list to store modified names
new_names_list = []

# Loop through each name in the original list
for name, number in new_list:
    # Find the index of the "org" substring starting from the end of the string
    org_index = name.rfind("org")

    # Get the substring starting from "org" and replace slashes with dots
    new_name = name[org_index:].replace("/", ".")

    # Add the modified name and number to the new list
    new_names_list.append([new_name, number])

# Print the new list
new_names_list

[['org.apache.commons.compress.zip.ExtraFieldUtils.java', '99'],
 ['org.apache.commons.compress.tar.TarBuffer.java', '125'],
 ['org.apache.commons.compress.tar.TarEntry.java', '94'],
 ['org.apache.commons.compress.zip.ZipLong.java', '104'],
 ['org.apache.commons.compress.tar.TarOutputStream.java', '100'],
 ['org.apache.commons.compress.zip.ZipShort.java', '105'],
 ['org.apache.commons.compress.tar.TarInputStream.java', '126'],
 ['org.apache.commons.compress.zip.UnixStat.java', '116'],
 ['org.apache.commons.compress.zip.UnrecognizedExtraField.java', '99'],
 ['org.apache.commons.compress.tar.TarUtils.java', '99'],
 ['org.apache.commons.compress.zip.ZipEntry.java', '100'],
 ['org.apache.commons.compress.zip.ZipOutputStream.java', '93'],
 ['org.apache.commons.compress.zip.AsiExtraField.java', '100'],
 ['org.apache.commons.compress.zip.ZipExtraField.java', '114'],
 ['org.apache.commons.compress.tar.TarConstants.java', '101'],
 ['org.apache.commons.compress.bzip2.CRC.java', '97'],
 ['org.apa

In [14]:
np.savetxt('budgets.txt', new_names_list, delimiter=';', fmt='%s')